## 22기 교육세션 [통계기초, 회귀분석] 과제

### 선형 회귀분석에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해주세요.

#### 데이터 불러오기

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [11]:
import pandas as pd 
data = pd.read_csv('/content/drive/MyDrive/학교/YBIGTA/통계기초_회귀분석/assignment.csv')

In [12]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [13]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [14]:
X = data.drop(["y"], axis=1)
y = data.y

In [15]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다. 
X = X.to_numpy()
y = y.to_numpy()

In [16]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [17]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

#### 정규방정식

In [30]:
import numpy as np
from numpy.linalg import inv 

In [34]:
def estimate_beta(X, y):
    # 세션자료 Unit 02, 다중선형회귀분석 LSE 파트 참고해주세요 :)
    designX = np.transpose(X)
    XtX = np.dot(designX, X)
    Xty = np.dot(designX, y)
    beta_hat = np.linalg.solve(XtX, Xty)
    
    return beta_hat

beta_hat = estimate_beta(X, y)
beta_hat

array([ 1.08810914,  0.01265822,  0.21664982,  0.01742894, -0.82514319])

#### 실제 값과 비교

In [21]:
from sklearn.linear_model import LinearRegression

In [27]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

In [28]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135655
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]
